using _2fpro.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;

using System.Web;

namespace _2fpro.Extension
{
    public static class ProductOpts
    {
        public static List<ProdOptionsViewModel> GetCloth()
        {

            var clothList = new List<ProdOptionsViewModel>(){
                new ProdOptionsViewModel{title="Энигма-01",imglink="/Content/em/tkani/enigma/Энигма-01-500x500.jpg",cat="энигма"},
                new ProdOptionsViewModel{title="Энигма-02",imglink="/Content/em/tkani/enigma/Энигма-02-500x500.jpg",cat="энигма"},
                new ProdOptionsViewModel{title="Энигма-03",imglink="/Content/em/tkani/enigma/Энигма-03-500x500.jpg",cat="энигма"},
                new ProdOptionsViewModel{title="Энигма-04",imglink="/Content/em/tkani/enigma/Энигма-04-500x500.jpg",cat="энигма"},
                new ProdOptionsViewModel{title="Энигма-05",imglink="/Content/em/tkani/enigma/Энигма-05-500x500.jpg",cat="энигма"},
                new ProdOptionsViewModel{title="Энигма-06",imglink="/Content/em/tkani/enigma/Энигма-06-500x500.jpg",cat="энигма"},
                new ProdOptionsViewModel{title="Энигма-07",imglink="/Content/em/tkani/enigma/Энигма-07-500x500.jpg",cat="энигма"},
                new ProdOptionsViewModel{title="Энигма-08",imglink="/Content/em/tkani/enigma/Энигма-08-500x500.jpg",cat="энигма"},
                new ProdOptionsViewModel{title="Энигма-11",imglink="/Content/em/tkani/enigma/Энигма-11-500x500.jpg",cat="энигма"},
                new ProdOptionsViewModel{title="Энигма-12",imglink="/Content/em/tkani/enigma/Энигма-12-500x500.jpg",cat="энигма"},
                new ProdOptionsViewModel{title="Энигма-13",imglink="/Content/em/tkani/enigma/Энигма-13-500x500.jpg",cat="энигма"},
                new ProdOptionsViewModel{title="Энигма-14",imglink="/Content/em/tkani/enigma/Энигма-14-500x500.jpg",cat="энигма"},
                new ProdOptionsViewModel{title="Энигма-15",imglink="/Content/em/tkani/enigma/Энигма-15-500x500.jpg",cat="энигма"},
                new ProdOptionsViewModel{title="Энигма-16",imglink="/Content/em/tkani/enigma/Энигма-16-500x500.jpg",cat="энигма"},
                new ProdOptionsViewModel{title="Энигма-17",imglink="/Content/em/tkani/enigma/Энигма-17-500x500.jpg",cat="энигма"},
                new ProdOptionsViewModel{title="Энигма-18",imglink="/Content/em/tkani/enigma/Энигма-18-500x500.jpg",cat="энигма"},
                new ProdOptionsViewModel{title="Энигма-19",imglink="/Content/em/tkani/enigma/Энигма-19-500x500.jpg",cat="энигма"},
                new ProdOptionsViewModel{title="Энигма-20",imglink="/Content/em/tkani/enigma/Энигма-20-500x500.jpg",cat="энигма"},
                new ProdOptionsViewModel{title="Энигма-21",imglink="/Content/em/tkani/enigma/Энигма-21-500x500.jpg",cat="энигма"},
                new ProdOptionsViewModel{title="Энигма-22",imglink="/Content/em/tkani/enigma/Энигма-22-500x500.jpg",cat="энигма"},
                new ProdOptionsViewModel{title="Энигма-23",imglink="/Content/em/tkani/enigma/Энигма-23-500x500.jpg",cat="энигма"},
                new ProdOptionsViewModel{title="Энигма-24",imglink="/Content/em/tkani/enigma/Энигма-24-500x500.jpg",cat="энигма"},
                new ProdOptionsViewModel{title="Энигма-25",imglink="/Content/em/tkani/enigma/Энигма-25-500x500.jpg",cat="энигма"},
                new ProdOptionsViewModel{title="Энигма-26",imglink="/Content/em/tkani/enigma/Энигма-26-500x500.jpg",cat="энигма"},
                new ProdOptionsViewModel{title="Энигма-27",imglink="/Content/em/tkani/enigma/Энигма-27-500x500.jpg",cat="энигма"},
                new ProdOptionsViewModel{title="Энигма-28",imglink="/Content/em/tkani/enigma/Энигма-28-500x500.jpg",cat="энигма"},
                new ProdOptionsViewModel{title="Энигма-29",imglink="/Content/em/tkani/enigma/Энигма-29-500x500.jpg",cat="энигма"},
                new ProdOptionsViewModel{title="Энигма-30",imglink="/Content/em/tkani/enigma/Энигма-30-500x500.jpg",cat="энигма"},
                new ProdOptionsViewModel{title="Энигма-31",imglink="/Content/em/tkani/enigma/Энигма-31-500x500.jpg",cat="энигма"},
                new ProdOptionsViewModel{title="Энигма-32",imglink="/Content/em/tkani/enigma/Энигма-32-500x500.jpg",cat="энигма"},
                new ProdOptionsViewModel{title="Энигма-33",imglink="/Content/em/tkani/enigma/Энигма-33-500x500.jpg",cat="энигма"},
                new ProdOptionsViewModel{title="Энигма-34",imglink="/Content/em/tkani/enigma/Энигма-34-500x500.jpg",cat="энигма"},
                new ProdOptionsViewModel{title="Энигма-35",imglink="/Content/em/tkani/enigma/Энигма-35-500x500.jpg",cat="энигма"},
                new ProdOptionsViewModel{title="Энигма-36",imglink="/Content/em/tkani/enigma/Энигма-36-500x500.jpg",cat="энигма"},





                new ProdOptionsViewModel{title="Валери-1",imglink="/Content/em/tkani/valeri/Валери-001-500x500.jpg",cat="валери"},
                new ProdOptionsViewModel{title="Валери-2",imglink="/Content/em/tkani/valeri/Валери-002-500x500.jpg",cat="валери"},
                new ProdOptionsViewModel{title="Валери-3",imglink="/Content/em/tkani/valeri/Валери-003-500x500.jpg",cat="валери"},
                new ProdOptionsViewModel{title="Валери-4",imglink="/Content/em/tkani/valeri/Валери-004-500x500.jpg",cat="валери"},
                new ProdOptionsViewModel{title="Валери-7",imglink="/Content/em/tkani/valeri/Валери-007-500x500.jpg",cat="валери"},
                new ProdOptionsViewModel{title="Валери-8",imglink="/Content/em/tkani/valeri/Валери-008-500x500.jpg",cat="валери"},
                new ProdOptionsViewModel{title="Валери-9",imglink="/Content/em/tkani/valeri/Валери-009-500x500.jpg",cat="валери"},
                new ProdOptionsViewModel{title="Валери-11",imglink="/Content/em/tkani/valeri/Валери-011-500x500.jpg",cat="валери"},
                new ProdOptionsViewModel{title="Валери-12",imglink="/Content/em/tkani/valeri/Валери-012-500x500.jpg",cat="валери"},
                new ProdOptionsViewModel{title="Валери-13",imglink="/Content/em/tkani/valeri/Валери-013-500x500.jpg",cat="валери"},
                new ProdOptionsViewModel{title="Валери-14",imglink="/Content/em/tkani/valeri/Валери-014-500x500.jpg",cat="валери"},
                new ProdOptionsViewModel{title="Валери-15",imglink="/Content/em/tkani/valeri/Валери-015-500x500.jpg",cat="валери"},
                new ProdOptionsViewModel{title="Валери-16",imglink="/Content/em/tkani/valeri/Валери-016-500x500.jpg",cat="валери"},
                new ProdOptionsViewModel{title="Валери-17",imglink="/Content/em/tkani/valeri/Валери-017-500x500.jpg",cat="валери"},
                new ProdOptionsViewModel{title="Валери-18",imglink="/Content/em/tkani/valeri/Валери-018-500x500.jpg",cat="валери"},
                new ProdOptionsViewModel{title="Валери-19",imglink="/Content/em/tkani/valeri/Валери-019-500x500.jpg",cat="валери"},
                new ProdOptionsViewModel{title="Валери-727",imglink="/Content/em/tkani/valeri/Валери-727-500x500.jpg",cat="валери"},
                new ProdOptionsViewModel{title="Валери-729",imglink="/Content/em/tkani/valeri/Валери-729-500x500.jpg",cat="валери"},
                new ProdOptionsViewModel{title="Валери-730",imglink="/Content/em/tkani/valeri/Валери-730-500x500.jpg",cat="валери"},
                new ProdOptionsViewModel{title="Валери-731",imglink="/Content/em/tkani/valeri/Валери-731-500x500.jpg",cat="валери"},


                new ProdOptionsViewModel{title="Софт-1",imglink="/Content/em/tkani/soft/Софт-01-500x500.jpg",cat="софт"},
                new ProdOptionsViewModel{title="Софт-2",imglink="/Content/em/tkani/soft/Софт-02-500x500.jpg",cat="софт"},
                new ProdOptionsViewModel{title="Софт-3",imglink="/Content/em/tkani/soft/Софт-03-500x500.jpg",cat="софт"},
                new ProdOptionsViewModel{title="Софт-4",imglink="/Content/em/tkani/soft/Софт-04-500x500.jpg",cat="софт"},
                new ProdOptionsViewModel{title="Софт-7",imglink="/Content/em/tkani/soft/Софт-07-500x500.jpg",cat="софт"},
                new ProdOptionsViewModel{title="Софт-9",imglink="/Content/em/tkani/soft/Софт-09-500x500.jpg",cat="софт"},
                new ProdOptionsViewModel{title="Софт-11",imglink="/Content/em/tkani/soft/Софт-11-500x500.jpg",cat="софт"},
                new ProdOptionsViewModel{title="Софт-13",imglink="/Content/em/tkani/soft/Софт-13-500x500.jpg",cat="софт"},
                new ProdOptionsViewModel{title="Софт-15",imglink="/Content/em/tkani/soft/Софт-15-500x500.jpg",cat="софт"},
                new ProdOptionsViewModel{title="Софт-16",imglink="/Content/em/tkani/soft/Софт-16-500x500.jpg",cat="софт"},
                new ProdOptionsViewModel{title="Софт-17",imglink="/Content/em/tkani/soft/Софт-17-500x500.jpg",cat="софт"},
                new ProdOptionsViewModel{title="Софт-18",imglink="/Content/em/tkani/soft/Софт-18-500x500.jpg",cat="софт"},
                new ProdOptionsViewModel{title="Софт-19",imglink="/Content/em/tkani/soft/Софт-19-500x500.jpg",cat="софт"},
                new ProdOptionsViewModel{title="Софт-20",imglink="/Content/em/tkani/soft/Софт-20-500x500.jpg",cat="софт"},
                new ProdOptionsViewModel{title="Софт-22",imglink="/Content/em/tkani/soft/Софт-22-500x500.jpg",cat="софт"},
                new ProdOptionsViewModel{title="Софт-24",imglink="/Content/em/tkani/soft/Софт-24-500x500.jpg",cat="софт"},
                new ProdOptionsViewModel{title="Софт-25",imglink="/Content/em/tkani/soft/Софт-25-500x500.jpg",cat="софт"},
                new ProdOptionsViewModel{title="Софт-26",imglink="/Content/em/tkani/soft/Софт-26-500x500.jpg",cat="софт"},
                new ProdOptionsViewModel{title="Софт-27",imglink="/Content/em/tkani/soft/Софт-27-500x500.jpg",cat="софт"},
                new ProdOptionsViewModel{title="Софт-729",imglink="/Content/em/tkani/soft/Софт-729-500x500.jpg",cat="софт"},
                new ProdOptionsViewModel{title="Софт-730",imglink="/Content/em/tkani/soft/Софт-730-500x500.jpg",cat="софт"},
                new ProdOptionsViewModel{title="Софт-731",imglink="/Content/em/tkani/soft/Софт-731-500x500.jpg",cat="софт"},



                new ProdOptionsViewModel{title="Форест-2",imglink="/Content/em/tkani/forest/Форест-2-500x500.jpg",cat="форест"},
                new ProdOptionsViewModel{title="Форест-6",imglink="/Content/em/tkani/forest/Форест-6-500x500.jpg",cat="форест"},
                new ProdOptionsViewModel{title="Форест-7",imglink="/Content/em/tkani/forest/Форест-7-500x500.jpg",cat="форест"},
                new ProdOptionsViewModel{title="Форест-8",imglink="/Content/em/tkani/forest/Форест-8-500x500.jpg",cat="форест"},
                new ProdOptionsViewModel{title="Форест-10",imglink="/Content/em/tkani/forest/Форест-10-500x500.jpg",cat="форест"},
                new ProdOptionsViewModel{title="Форест-13",imglink="/Content/em/tkani/forest/Форест-13-500x500.jpg",cat="форест"},
                new ProdOptionsViewModel{title="Форест-16",imglink="/Content/em/tkani/forest/Форест-16-500x500.jpg",cat="форест"},
                new ProdOptionsViewModel{title="Форест-17",imglink="/Content/em/tkani/forest/Форест-17-500x500.jpg",cat="форест"},
                new ProdOptionsViewModel{title="Форест-18",imglink="/Content/em/tkani/forest/Форест-18-500x500.jpg",cat="форест"},
                new ProdOptionsViewModel{title="Форест-503",imglink="/Content/em/tkani/forest/Форест-503-500x500.jpg",cat="форест"},
                new ProdOptionsViewModel{title="Форест-509",imglink="/Content/em/tkani/forest/Форест-509-500x500.jpg",cat="форест"},
                new ProdOptionsViewModel{title="Форест-510",imglink="/Content/em/tkani/forest/Форест-510-500x500.jpg",cat="форест"},
                new ProdOptionsViewModel{title="Форест-514",imglink="/Content/em/tkani/forest/Форест-514-500x500.jpg",cat="форест"},
                new ProdOptionsViewModel{title="Форест-520",imglink="/Content/em/tkani/forest/Форест-520-500x500.jpg",cat="форест"},
                new ProdOptionsViewModel{title="Форест-521",imglink="/Content/em/tkani/forest/Форест-521-500x500.jpg",cat="форест"},
                new ProdOptionsViewModel{title="Форест-522",imglink="/Content/em/tkani/forest/Форест-522-500x500.jpg",cat="форест"},
                new ProdOptionsViewModel{title="Форест-528",imglink="/Content/em/tkani/forest/Форест-528-500x500.jpg",cat="форест"},
                new ProdOptionsViewModel{title="Форест-531",imglink="/Content/em/tkani/forest/Форест-531-500x500.jpg",cat="форест"},
                new ProdOptionsViewModel{title="Форест-533",imglink="/Content/em/tkani/forest/Форест-533-500x500.jpg",cat="форест"},
                new ProdOptionsViewModel{title="Форест-536",imglink="/Content/em/tkani/forest/Форест-536-500x500.jpg",cat="форест"},
                new ProdOptionsViewModel{title="Форест-540",imglink="/Content/em/tkani/forest/Форест-540-500x500.jpg",cat="форест"},
                new ProdOptionsViewModel{title="Форест-541",imglink="/Content/em/tkani/forest/Форест-541-500x500.jpg",cat="форест"},
                new ProdOptionsViewModel{title="Форест-543",imglink="/Content/em/tkani/forest/Форест-543-500x500.jpg",cat="форест"},
                new ProdOptionsViewModel{title="Форест-560",imglink="/Content/em/tkani/forest/Форест-560-500x500.jpg",cat="форест"},
                new ProdOptionsViewModel{title="Форест-562",imglink="/Content/em/tkani/forest/Форест-562-500x500.jpg",cat="форест"},
                new ProdOptionsViewModel{title="Форест-564",imglink="/Content/em/tkani/forest/Форест-564-500x500.jpg",cat="форест"},
                new ProdOptionsViewModel{title="Форест-726",imglink="/Content/em/tkani/forest/Форест-726-500x500.jpg",cat="форест"},
                new ProdOptionsViewModel{title="Форест-727",imglink="/Content/em/tkani/forest/Форест-727-500x500.jpg",cat="форест"},
                new ProdOptionsViewModel{title="Форест-728",imglink="/Content/em/tkani/forest/Форест-728-500x500.jpg",cat="форест"},
                new ProdOptionsViewModel{title="Форест-729",imglink="/Content/em/tkani/forest/Форест-729-500x500.jpg",cat="форест"},
                new ProdOptionsViewModel{title="Форест-730",imglink="/Content/em/tkani/forest/Форест-730-500x500.jpg",cat="форест"},
                new ProdOptionsViewModel{title="Форест-731",imglink="/Content/em/tkani/forest/Форест-731-500x500.jpg",cat="форест"},
                new ProdOptionsViewModel{title="Форест-732",imglink="/Content/em/tkani/forest/Форест-732-500x500.jpg",cat="форест"},
                new ProdOptionsViewModel{title="Форест-740",imglink="/Content/em/tkani/forest/Форест-740-500x500.jpg",cat="форест"},
                new ProdOptionsViewModel{title="Форест-741",imglink="/Content/em/tkani/forest/Форест-741-500x500.jpg",cat="форест"},


                new ProdOptionsViewModel{title="Сахара-4",imglink="/Content/em/tkani/sahara/Сахара-4-500x500.jpg",cat="сахара"},
                new ProdOptionsViewModel{title="Сахара-5",imglink="/Content/em/tkani/sahara/Сахара-5-500x500.jpg",cat="сахара"},
                new ProdOptionsViewModel{title="Сахара-6",imglink="/Content/em/tkani/sahara/Сахара-6-500x500.jpg",cat="сахара"},
                new ProdOptionsViewModel{title="Сахара-7",imglink="/Content/em/tkani/sahara/Сахара-7-500x500.jpg",cat="сахара"},
                new ProdOptionsViewModel{title="Сахара-12",imglink="/Content/em/tkani/sahara/Сахара-12-500x500.jpg",cat="сахара"},
                new ProdOptionsViewModel{title="Сахара-17",imglink="/Content/em/tkani/sahara/Сахара-17-500x500.jpg",cat="сахара"},
                new ProdOptionsViewModel{title="Сахара-23",imglink="/Content/em/tkani/sahara/Сахара-23-500x500.jpg",cat="сахара"},
                new ProdOptionsViewModel{title="Сахара-26",imglink="/Content/em/tkani/sahara/Сахара-26-500x500.jpg",cat="сахара"},
                new ProdOptionsViewModel{title="Сахара-27",imglink="/Content/em/tkani/sahara/Сахара-27-500x500.jpg",cat="сахара"},
                new ProdOptionsViewModel{title="Сахара-30",imglink="/Content/em/tkani/sahara/Сахара-30-500x500.jpg",cat="сахара"},
                new ProdOptionsViewModel{title="Сахара-31",imglink="/Content/em/tkani/sahara/Сахара-31-500x500.jpg",cat="сахара"},
                new ProdOptionsViewModel{title="Сахара-32",imglink="/Content/em/tkani/sahara/Сахара-32-500x500.jpg",cat="сахара"},
                new ProdOptionsViewModel{title="Сахара-33",imglink="/Content/em/tkani/sahara/Сахара-33-500x500.jpg",cat="сахара"},
                new ProdOptionsViewModel{title="Сахара-37",imglink="/Content/em/tkani/sahara/Сахара-37-500x500.jpg",cat="сахара"},
                new ProdOptionsViewModel{title="Сахара-38",imglink="/Content/em/tkani/sahara/Сахара-38-500x500.jpg",cat="сахара"},
                new ProdOptionsViewModel{title="Сахара-39",imglink="/Content/em/tkani/sahara/Сахара-39-500x500.jpg",cat="сахара"},
                new ProdOptionsViewModel{title="Сахара-41",imglink="/Content/em/tkani/sahara/Сахара-41-500x500.jpg",cat="сахара"},
                new ProdOptionsViewModel{title="Сахара-45",imglink="/Content/em/tkani/sahara/Сахара-45-500x500.jpg",cat="сахара"},
                new ProdOptionsViewModel{title="Сахара-46",imglink="/Content/em/tkani/sahara/Сахара-46-500x500.jpg",cat="сахара"},
                new ProdOptionsViewModel{title="Сахара-47",imglink="/Content/em/tkani/sahara/Сахара-47-500x500.jpg",cat="сахара"},
                new ProdOptionsViewModel{title="Сахара-48",imglink="/Content/em/tkani/sahara/Сахара-48-500x500.jpg",cat="сахара"},
                new ProdOptionsViewModel{title="Сахара-49",imglink="/Content/em/tkani/sahara/Сахара-49-500x500.jpg",cat="сахара"},


                new ProdOptionsViewModel{title="Дублин-2",imglink="/Content/em/tkani/dublin/Дублин-02-500x500.jpg",cat="дублин"},
                new ProdOptionsViewModel{title="Дублин-4",imglink="/Content/em/tkani/dublin/Дублин-04-500x500.jpg",cat="дублин"},
                new ProdOptionsViewModel{title="Дублин-5",imglink="/Content/em/tkani/dublin/Дублин-05-500x500.jpg",cat="дублин"},
                new ProdOptionsViewModel{title="Дублин-7",imglink="/Content/em/tkani/dublin/Дублин-07-500x500.jpg",cat="дублин"},
                new ProdOptionsViewModel{title="Дублин-8",imglink="/Content/em/tkani/dublin/Дублин-08-500x500.jpg",cat="дублин"},
                new ProdOptionsViewModel{title="Дублин-9",imglink="/Content/em/tkani/dublin/Дублин-09-500x500.jpg",cat="дублин"},
                new ProdOptionsViewModel{title="Дублин-12",imglink="/Content/em/tkani/dublin/Дублин-12-500x500.jpg",cat="дублин"},
                new ProdOptionsViewModel{title="Дублин-14",imglink="/Content/em/tkani/dublin/Дублин-14-500x500.jpg",cat="дублин"},
                new ProdOptionsViewModel{title="Дублин-15",imglink="/Content/em/tkani/dublin/Дублин-15-500x500.jpg",cat="дублин"},
                new ProdOptionsViewModel{title="Дублин-17",imglink="/Content/em/tkani/dublin/Дублин-17-500x500.jpg",cat="дублин"},
                new ProdOptionsViewModel{title="Дублин-20",imglink="/Content/em/tkani/dublin/Дублин-20-500x500.jpg",cat="дублин"},



                new ProdOptionsViewModel{title="Бланд-1",imglink="/Content/em/tkani/bland/Бланд-01-500x500.jpg",cat="бланд"},
                new ProdOptionsViewModel{title="Бланд-2",imglink="/Content/em/tkani/bland/Бланд-02-500x500.jpg",cat="бланд"},
                new ProdOptionsViewModel{title="Бланд-3",imglink="/Content/em/tkani/bland/Бланд-03-500x500.jpg",cat="бланд"},
                new ProdOptionsViewModel{title="Бланд-4",imglink="/Content/em/tkani/bland/Бланд-04-500x500.jpg",cat="бланд"},
                new ProdOptionsViewModel{title="Бланд-12",imglink="/Content/em/tkani/bland/Бланд-12-500x500.jpg",cat="бланд"},
                new ProdOptionsViewModel{title="Бланд-514",imglink="/Content/em/tkani/bland/Бланд-514-500x500.jpg",cat="бланд"},
                new ProdOptionsViewModel{title="Бланд-520",imglink="/Content/em/tkani/bland/Бланд-520-500x500.jpg",cat="бланд"},
                new ProdOptionsViewModel{title="Бланд-536",imglink="/Content/em/tkani/bland/Бланд-536-500x500.jpg",cat="бланд"},
                new ProdOptionsViewModel{title="Бланд-540",imglink="/Content/em/tkani/bland/Бланд-540-500x500.jpg",cat="бланд"},
                new ProdOptionsViewModel{title="Бланд-562",imglink="/Content/em/tkani/bland/Бланд-562-500x500.jpg",cat="бланд"},
                new ProdOptionsViewModel{title="Бланд-564",imglink="/Content/em/tkani/bland/Бланд-564-500x500.jpg",cat="бланд"},
                new ProdOptionsViewModel{title="Бланд-601",imglink="/Content/em/tkani/bland/Бланд-601-500x500.jpg",cat="бланд"},
                new ProdOptionsViewModel{title="Бланд-602",imglink="/Content/em/tkani/bland/Бланд-602-500x500.jpg",cat="бланд"},
                new ProdOptionsViewModel{title="Бланд-610",imglink="/Content/em/tkani/bland/Бланд-610-500x500.jpg",cat="бланд"},
                new ProdOptionsViewModel{title="Бланд-618",imglink="/Content/em/tkani/bland/Бланд-618-500x500.jpg",cat="бланд"},
                new ProdOptionsViewModel{title="Бланд-727",imglink="/Content/em/tkani/bland/Бланд-727-500x500.jpg",cat="бланд"},
                new ProdOptionsViewModel{title="Бланд-729",imglink="/Content/em/tkani/bland/Бланд-729-500x500.jpg",cat="бланд"},
                new ProdOptionsViewModel{title="Бланд-730",imglink="/Content/em/tkani/bland/Бланд-730-500x500.jpg",cat="бланд"},
                new ProdOptionsViewModel{title="Бланд-731",imglink="/Content/em/tkani/bland/Бланд-731-500x500.jpg",cat="бланд"},


                new ProdOptionsViewModel{title="Корд-17",imglink="/Content/em/tkani/kord/Корд-017-500x500.jpg",cat="корд"},
                new ProdOptionsViewModel{title="Корд-101",imglink="/Content/em/tkani/kord/Корд-101-500x500.jpg",cat="корд"},
                new ProdOptionsViewModel{title="Корд-102",imglink="/Content/em/tkani/kord/Корд-102-500x500.jpg",cat="корд"},
                new ProdOptionsViewModel{title="Корд-103",imglink="/Content/em/tkani/kord/Корд-103-500x500.jpg",cat="корд"},
                new ProdOptionsViewModel{title="Корд-104",imglink="/Content/em/tkani/kord/Корд-104-500x500.jpg",cat="корд"},
                new ProdOptionsViewModel{title="Корд-107",imglink="/Content/em/tkani/kord/Корд-107-500x500.jpg",cat="корд"},
                new ProdOptionsViewModel{title="Корд-109",imglink="/Content/em/tkani/kord/Корд-109-500x500.jpg",cat="корд"},
                new ProdOptionsViewModel{title="Корд-116",imglink="/Content/em/tkani/kord/Корд-116-500x500.jpg",cat="корд"},
                new ProdOptionsViewModel{title="Корд-126",imglink="/Content/em/tkani/kord/Корд-126-500x500.jpg",cat="корд"},
                new ProdOptionsViewModel{title="Корд-129",imglink="/Content/em/tkani/kord/Корд-129-500x500.jpg",cat="корд"},
                new ProdOptionsViewModel{title="Корд-729",imglink="/Content/em/tkani/kord/Корд-729-500x500.jpg",cat="корд"},
                new ProdOptionsViewModel{title="Корд-730",imglink="/Content/em/tkani/kord/Корд-730-500x500.jpg",cat="корд"},
                new ProdOptionsViewModel{title="Корд-731",imglink="/Content/em/tkani/kord/Корд-731-500x500.jpg",cat="корд"},


                 new ProdOptionsViewModel{title="Норд-6",imglink="/Content/em/tkani/nord/Норд-006-500x500.jpg",cat="норд"},
                 new ProdOptionsViewModel{title="Норд-8",imglink="/Content/em/tkani/nord/Норд-008-500x500.jpg",cat="норд"},
                 new ProdOptionsViewModel{title="Норд-25",imglink="/Content/em/tkani/nord/Норд-025-500x500.jpg",cat="норд"},
                 new ProdOptionsViewModel{title="Норд-33",imglink="/Content/em/tkani/nord/Норд-033-500x500.jpg",cat="норд"},
                 new ProdOptionsViewModel{title="Норд-34",imglink="/Content/em/tkani/nord/Норд-034-500x500.jpg",cat="норд"},
                 new ProdOptionsViewModel{title="Норд-57",imglink="/Content/em/tkani/nord/Норд-057-500x500.jpg",cat="норд"},
                 new ProdOptionsViewModel{title="Норд-702",imglink="/Content/em/tkani/nord/Норд-702-500x500.jpg",cat="норд"},
                 new ProdOptionsViewModel{title="Норд-704",imglink="/Content/em/tkani/nord/Норд-704-500x500.jpg",cat="норд"},
                 new ProdOptionsViewModel{title="Норд-727",imglink="/Content/em/tkani/nord/Норд-727-500x500.jpg",cat="норд"},
                 new ProdOptionsViewModel{title="Норд-729",imglink="/Content/em/tkani/nord/Норд-729-500x500.jpg",cat="норд"},
                 new ProdOptionsViewModel{title="Норд-730",imglink="/Content/em/tkani/nord/Норд-730-500x500.jpg",cat="норд"},
                 new ProdOptionsViewModel{title="Норд-731",imglink="/Content/em/tkani/nord/Норд-731-500x500.jpg",cat="норд"},
                 new ProdOptionsViewModel{title="Норд-801",imglink="/Content/em/tkani/nord/Норд-801-500x500.jpg",cat="норд"},
                 new ProdOptionsViewModel{title="Норд-802",imglink="/Content/em/tkani/nord/Норд-802-500x500.jpg",cat="норд"},
                 new ProdOptionsViewModel{title="Норд-803",imglink="/Content/em/tkani/nord/Норд-803-500x500.jpg",cat="норд"},
                 new ProdOptionsViewModel{title="Норд-804",imglink="/Content/em/tkani/nord/Норд-804-500x500.jpg",cat="норд"},
                 new ProdOptionsViewModel{title="Норд-805",imglink="/Content/em/tkani/nord/Норд-805-500x500.jpg",cat="норд"},
                 new ProdOptionsViewModel{title="Норд-806",imglink="/Content/em/tkani/nord/Норд-806-500x500.jpg",cat="норд"},
                 new ProdOptionsViewModel{title="Норд-807",imglink="/Content/em/tkani/nord/Норд-807-500x500.jpg",cat="норд"},
                 new ProdOptionsViewModel{title="Норд-808",imglink="/Content/em/tkani/nord/Норд-808-500x500.jpg",cat="норд"},
                 new ProdOptionsViewModel{title="Норд-809",imglink="/Content/em/tkani/nord/Норд-809-500x500.jpg",cat="норд"},
                 new ProdOptionsViewModel{title="Норд-810",imglink="/Content/em/tkani/nord/Норд-810-500x500.jpg",cat="норд"},
                 new ProdOptionsViewModel{title="Норд-811",imglink="/Content/em/tkani/nord/Норд-811-500x500.jpg",cat="норд"},
                 new ProdOptionsViewModel{title="Норд-812",imglink="/Content/em/tkani/nord/Норд-812-500x500.jpg",cat="норд"},
                 new ProdOptionsViewModel{title="Норд-813",imglink="/Content/em/tkani/nord/Норд-813-500x500.jpg",cat="норд"},
                 new ProdOptionsViewModel{title="Норд-814",imglink="/Content/em/tkani/nord/Норд-814-500x500.jpg",cat="норд"},
                 new ProdOptionsViewModel{title="Норд-815",imglink="/Content/em/tkani/nord/Норд-815-500x500.jpg",cat="норд"},
                 new ProdOptionsViewModel{title="Норд-816",imglink="/Content/em/tkani/nord/Норд-816-500x500.jpg",cat="норд"},
                 new ProdOptionsViewModel{title="Норд-817",imglink="/Content/em/tkani/nord/Норд-817-500x500.jpg",cat="норд"},
                 new ProdOptionsViewModel{title="Норд-818",imglink="/Content/em/tkani/nord/Норд-818-500x500.jpg",cat="норд"},
                 new ProdOptionsViewModel{title="Норд-819",imglink="/Content/em/tkani/nord/Норд-819-500x500.jpg",cat="норд"},
                 new ProdOptionsViewModel{title="Норд-821",imglink="/Content/em/tkani/nord/Норд-821-500x500.jpg",cat="норд"},
                 new ProdOptionsViewModel{title="Норд-822",imglink="/Content/em/tkani/nord/Норд-822-500x500.jpg",cat="норд"},
                 new ProdOptionsViewModel{title="Норд-823",imglink="/Content/em/tkani/nord/Норд-823-500x500.jpg",cat="норд"},
                 new ProdOptionsViewModel{title="Норд-824",imglink="/Content/em/tkani/nord/Норд-824-500x500.jpg",cat="норд"},
                 new ProdOptionsViewModel{title="Норд-825",imglink="/Content/em/tkani/nord/Норд-825-500x500.jpg",cat="норд"},
                 new ProdOptionsViewModel{title="Норд-826",imglink="/Content/em/tkani/nord/Норд-826-500x500.jpg",cat="норд"},
                 new ProdOptionsViewModel{title="Норд-827",imglink="/Content/em/tkani/nord/Норд-827-500x500.jpg",cat="норд"},
                 new ProdOptionsViewModel{title="Норд-828",imglink="/Content/em/tkani/nord/Норд-828-500x500.jpg",cat="норд"},
                 new ProdOptionsViewModel{title="Норд-830",imglink="/Content/em/tkani/nord/Норд-830-500x500.jpg",cat="норд"},
                 new ProdOptionsViewModel{title="Норд-831",imglink="/Content/em/tkani/nord/Норд-831-500x500.jpg",cat="норд"},
                 new ProdOptionsViewModel{title="Норд-832",imglink="/Content/em/tkani/nord/Норд-832-500x500.jpg",cat="норд"},
                 new ProdOptionsViewModel{title="Норд-833",imglink="/Content/em/tkani/nord/Норд-833-500x500.jpg",cat="норд"},
                 new ProdOptionsViewModel{title="Норд-834",imglink="/Content/em/tkani/nord/Норд-834-500x500.jpg",cat="норд"},
                 new ProdOptionsViewModel{title="Норд-850",imglink="/Content/em/tkani/nord/Норд-850-500x500.jpg",cat="норд"},



                 new ProdOptionsViewModel{title="Вельвет люкс-1",imglink="/Content/em/tkani/velvet/velvetlux01.jpg",cat="вельвет"},
                 new ProdOptionsViewModel{title="Вельвет люкс-2",imglink="/Content/em/tkani/velvet/velvetlux02.jpg",cat="вельвет"},
                 new ProdOptionsViewModel{title="Вельвет люкс-3",imglink="/Content/em/tkani/velvet/velvetlux03.jpg",cat="вельвет"},
                 new ProdOptionsViewModel{title="Вельвет люкс-4",imglink="/Content/em/tkani/velvet/velvetlux04.jpg",cat="вельвет"},
                 new ProdOptionsViewModel{title="Вельвет люкс-5",imglink="/Content/em/tkani/velvet/velvetlux05.jpg",cat="вельвет"},
                 new ProdOptionsViewModel{title="Вельвет люкс-6",imglink="/Content/em/tkani/velvet/velvetlux06.jpg",cat="вельвет"},
                 new ProdOptionsViewModel{title="Вельвет люкс-7",imglink="/Content/em/tkani/velvet/velvetlux07.jpg",cat="вельвет"},
                 new ProdOptionsViewModel{title="Вельвет люкс-8",imglink="/Content/em/tkani/velvet/velvetlux08.jpg",cat="вельвет"},
                 new ProdOptionsViewModel{title="Вельвет люкс-9",imglink="/Content/em/tkani/velvet/velvetlux09.jpg",cat="вельвет"},
                 new ProdOptionsViewModel{title="Вельвет люкс-10",imglink="/Content/em/tkani/velvet/velvetlux10.jpg",cat="вельвет"},
                 new ProdOptionsViewModel{title="Вельвет люкс-11",imglink="/Content/em/tkani/velvet/velvetlux11.jpg",cat="вельвет"},
                 new ProdOptionsViewModel{title="Вельвет люкс-12",imglink="/Content/em/tkani/velvet/velvetlux12.jpg",cat="вельвет"},
                 new ProdOptionsViewModel{title="Вельвет люкс-13",imglink="/Content/em/tkani/velvet/velvetlux13.jpg",cat="вельвет"},
                 new ProdOptionsViewModel{title="Вельвет люкс-14",imglink="/Content/em/tkani/velvet/velvetlux14.jpg",cat="вельвет"},
                 new ProdOptionsViewModel{title="Вельвет люкс-15",imglink="/Content/em/tkani/velvet/velvetlux15.jpg",cat="вельвет"},
                 new ProdOptionsViewModel{title="Вельвет люкс-16",imglink="/Content/em/tkani/velvet/velvetlux16.jpg",cat="вельвет"},
                 new ProdOptionsViewModel{title="Вельвет люкс-17",imglink="/Content/em/tkani/velvet/velvetlux17.jpg",cat="вельвет"},
                 new ProdOptionsViewModel{title="Вельвет люкс-18",imglink="/Content/em/tkani/velvet/velvetlux18.jpg",cat="вельвет"},
                 new ProdOptionsViewModel{title="Вельвет люкс-19",imglink="/Content/em/tkani/velvet/velvetlux19.jpg",cat="вельвет"},
                 new ProdOptionsViewModel{title="Вельвет люкс-20",imglink="/Content/em/tkani/velvet/velvetlux20.jpg",cat="вельвет"},
                 new ProdOptionsViewModel{title="Вельвет люкс-21",imglink="/Content/em/tkani/velvet/velvetlux21.jpg",cat="вельвет"},
                 new ProdOptionsViewModel{title="Вельвет люкс-22",imglink="/Content/em/tkani/velvet/velvetlux22.jpg",cat="вельвет"},
                 new ProdOptionsViewModel{title="Вельвет люкс-23",imglink="/Content/em/tkani/velvet/velvetlux23.jpg",cat="вельвет"},
                 new ProdOptionsViewModel{title="Вельвет люкс-24",imglink="/Content/em/tkani/velvet/velvetlux24.jpg",cat="вельвет"},
                 new ProdOptionsViewModel{title="Вельвет люкс-25",imglink="/Content/em/tkani/velvet/velvetlux25.jpg",cat="вельвет"},
                 new ProdOptionsViewModel{title="Вельвет люкс-26",imglink="/Content/em/tkani/velvet/velvetlux26.jpg",cat="вельвет"},
                 new ProdOptionsViewModel{title="Вельвет люкс-27",imglink="/Content/em/tkani/velvet/velvetlux27.jpg",cat="вельвет"},
                 new ProdOptionsViewModel{title="Вельвет люкс-28",imglink="/Content/em/tkani/velvet/velvetlux28.jpg",cat="вельвет"},
                 new ProdOptionsViewModel{title="Вельвет люкс-29",imglink="/Content/em/tkani/velvet/velvetlux29.jpg",cat="вельвет"},
                 new ProdOptionsViewModel{title="Вельвет люкс-30",imglink="/Content/em/tkani/velvet/velvetlux30.jpg",cat="вельвет"},
                 new ProdOptionsViewModel{title="Вельвет люкс-31",imglink="/Content/em/tkani/velvet/velvetlux31.jpg",cat="вельвет"},
                 new ProdOptionsViewModel{title="Вельвет люкс-32",imglink="/Content/em/tkani/velvet/velvetlux32.jpg",cat="вельвет"},
                 new ProdOptionsViewModel{title="Вельвет люкс-33",imglink="/Content/em/tkani/velvet/velvetlux33.jpg",cat="вельвет"},
                 new ProdOptionsViewModel{title="Вельвет люкс-34",imglink="/Content/em/tkani/velvet/velvetlux34.jpg",cat="вельвет"},
                 new ProdOptionsViewModel{title="Вельвет люкс-35",imglink="/Content/em/tkani/velvet/velvetlux35.jpg",cat="вельвет"},
                 new ProdOptionsViewModel{title="Вельвет люкс-36",imglink="/Content/em/tkani/velvet/velvetlux36.jpg",cat="вельвет"},
                 new ProdOptionsViewModel{title="Вельвет люкс-37",imglink="/Content/em/tkani/velvet/velvetlux37.jpg",cat="вельвет"},
                 new ProdOptionsViewModel{title="Вельвет люкс-38",imglink="/Content/em/tkani/velvet/velvetlux38.jpg",cat="вельвет"},
                 new ProdOptionsViewModel{title="Вельвет люкс-39",imglink="/Content/em/tkani/velvet/velvetlux39.jpg",cat="вельвет"},
                 new ProdOptionsViewModel{title="Вельвет люкс-40",imglink="/Content/em/tkani/velvet/velvetlux40.jpg",cat="вельвет"},
                 new ProdOptionsViewModel{title="Вельвет люкс-41",imglink="/Content/em/tkani/velvet/velvetlux41.jpg",cat="вельвет"},
                 new ProdOptionsViewModel{title="Вельвет люкс-42",imglink="/Content/em/tkani/velvet/velvetlux42.jpg",cat="вельвет"},
                 new ProdOptionsViewModel{title="Вельвет люкс-43",imglink="/Content/em/tkani/velvet/velvetlux43.jpg",cat="вельвет"},
                 new ProdOptionsViewModel{title="Вельвет люкс-44",imglink="/Content/em/tkani/velvet/velvetlux44.jpg",cat="вельвет"},
                 new ProdOptionsViewModel{title="Вельвет люкс-45",imglink="/Content/em/tkani/velvet/velvetlux45.jpg",cat="вельвет"},
                 new ProdOptionsViewModel{title="Вельвет люкс-46",imglink="/Content/em/tkani/velvet/velvetlux46.jpg",cat="вельвет"},
                 new ProdOptionsViewModel{title="Вельвет люкс-47",imglink="/Content/em/tkani/velvet/velvetlux47.jpg",cat="вельвет"},
                 new ProdOptionsViewModel{title="Вельвет люкс-48",imglink="/Content/em/tkani/velvet/velvetlux48.jpg",cat="вельвет"},
                 new ProdOptionsViewModel{title="Вельвет люкс-49",imglink="/Content/em/tkani/velvet/velvetlux49.jpg",cat="вельвет"},
                 new ProdOptionsViewModel{title="Вельвет люкс-50",imglink="/Content/em/tkani/velvet/velvetlux50.jpg",cat="вельвет"},
                 new ProdOptionsViewModel{title="Вельвет люкс-51",imglink="/Content/em/tkani/velvet/velvetlux51.jpg",cat="вельвет"},
                 new ProdOptionsViewModel{title="Вельвет люкс-52",imglink="/Content/em/tkani/velvet/velvetlux52.jpg",cat="вельвет"},
                 new ProdOptionsViewModel{title="Вельвет люкс-53",imglink="/Content/em/tkani/velvet/velvetlux53.jpg",cat="вельвет"},
                 new ProdOptionsViewModel{title="Вельвет люкс-54",imglink="/Content/em/tkani/velvet/velvetlux54.jpg",cat="вельвет"},
                 new ProdOptionsViewModel{title="Вельвет люкс-55",imglink="/Content/em/tkani/velvet/velvetlux55.jpg",cat="вельвет"},
                 new ProdOptionsViewModel{title="Вельвет люкс-56",imglink="/Content/em/tkani/velvet/velvetlux56.jpg",cat="вельвет"},
                 new ProdOptionsViewModel{title="Вельвет люкс-57",imglink="/Content/em/tkani/velvet/velvetlux57.jpg",cat="вельвет"},
                 new ProdOptionsViewModel{title="Вельвет люкс-58",imglink="/Content/em/tkani/velvet/velvetlux58.jpg",cat="вельвет"},
                 new ProdOptionsViewModel{title="Вельвет люкс-59",imglink="/Content/em/tkani/velvet/velvetlux59.jpg",cat="вельвет"},
                 new ProdOptionsViewModel{title="Вельвет люкс-60",imglink="/Content/em/tkani/velvet/velvetlux60.jpg",cat="вельвет"},
                 new ProdOptionsViewModel{title="Вельвет люкс-61",imglink="/Content/em/tkani/velvet/velvetlux61.jpg",cat="вельвет"},
                 new ProdOptionsViewModel{title="Вельвет люкс-62",imglink="/Content/em/tkani/velvet/velvetlux62.jpg",cat="вельвет"},
                 new ProdOptionsViewModel{title="Вельвет люкс-63",imglink="/Content/em/tkani/velvet/velvetlux63.jpg",cat="вельвет"},
                 new ProdOptionsViewModel{title="Вельвет люкс-64",imglink="/Content/em/tkani/velvet/velvetlux64.jpg",cat="вельвет"},
                 new ProdOptionsViewModel{title="Вельвет люкс-65",imglink="/Content/em/tkani/velvet/velvetlux65.jpg",cat="вельвет"},
                 new ProdOptionsViewModel{title="Вельвет люкс-66",imglink="/Content/em/tkani/velvet/velvetlux66.jpg",cat="вельвет"},
                 new ProdOptionsViewModel{title="Вельвет люкс-67",imglink="/Content/em/tkani/velvet/velvetlux67.jpg",cat="вельвет"},
                 new ProdOptionsViewModel{title="Вельвет люкс-68",imglink="/Content/em/tkani/velvet/velvetlux68.jpg",cat="вельвет"},
                 new ProdOptionsViewModel{title="Вельвет люкс-69",imglink="/Content/em/tkani/velvet/velvetlux69.jpg",cat="вельвет"},
                 new ProdOptionsViewModel{title="Вельвет люкс-70",imglink="/Content/em/tkani/velvet/velvetlux70.jpg",cat="вельвет"},
                 new ProdOptionsViewModel{title="Вельвет люкс-71",imglink="/Content/em/tkani/velvet/velvetlux71.jpg",cat="вельвет"},
                 new ProdOptionsViewModel{title="Вельвет люкс-72",imglink="/Content/em/tkani/velvet/velvetlux72.jpg",cat="вельвет"},
                 new ProdOptionsViewModel{title="Вельвет люкс-73",imglink="/Content/em/tkani/velvet/velvetlux73.jpg",cat="вельвет"},
                 new ProdOptionsViewModel{title="Вельвет люкс-74",imglink="/Content/em/tkani/velvet/velvetlux74.jpg",cat="вельвет"},
                 new ProdOptionsViewModel{title="Вельвет люкс-75",imglink="/Content/em/tkani/velvet/velvetlux75.jpg",cat="вельвет"},
                 new ProdOptionsViewModel{title="Вельвет люкс-76",imglink="/Content/em/tkani/velvet/velvetlux76.jpg",cat="вельвет"},
                 new ProdOptionsViewModel{title="Вельвет люкс-77",imglink="/Content/em/tkani/velvet/velvetlux77.jpg",cat="вельвет"},
                 new ProdOptionsViewModel{title="Вельвет люкс-78",imglink="/Content/em/tkani/velvet/velvetlux78.jpg",cat="вельвет"},
                 new ProdOptionsViewModel{title="Вельвет люкс-79",imglink="/Content/em/tkani/velvet/velvetlux79.jpg",cat="вельвет"},
                 new ProdOptionsViewModel{title="Вельвет люкс-80",imglink="/Content/em/tkani/velvet/velvetlux80.jpg",cat="вельвет"},
                 new ProdOptionsViewModel{title="Вельвет люкс-81",imglink="/Content/em/tkani/velvet/velvetlux81.jpg",cat="вельвет"},
                 new ProdOptionsViewModel{title="Вельвет люкс-82",imglink="/Content/em/tkani/velvet/velvetlux82.jpg",cat="вельвет"},
                 new ProdOptionsViewModel{title="Вельвет люкс-83",imglink="/Content/em/tkani/velvet/velvetlux83.jpg",cat="вельвет"},
                 new ProdOptionsViewModel{title="Вельвет люкс-84",imglink="/Content/em/tkani/velvet/velvetlux84.jpg",cat="вельвет"},
                 new ProdOptionsViewModel{title="Вельвет люкс-85",imglink="/Content/em/tkani/velvet/velvetlux85.jpg",cat="вельвет"},
                 new ProdOptionsViewModel{title="Вельвет люкс-86",imglink="/Content/em/tkani/velvet/velvetlux86.jpg",cat="вельвет"},
                 new ProdOptionsViewModel{title="Вельвет люкс-87",imglink="/Content/em/tkani/velvet/velvetlux87.jpg",cat="вельвет"},
                 new ProdOptionsViewModel{title="Вельвет люкс-88",imglink="/Content/em/tkani/velvet/velvetlux88.jpg",cat="вельвет"},
                 new ProdOptionsViewModel{title="Вельвет люкс-89",imglink="/Content/em/tkani/velvet/velvetlux89.jpg",cat="вельвет"},
                 new ProdOptionsViewModel{title="Вельвет люкс-90",imglink="/Content/em/tkani/velvet/velvetlux90.jpg",cat="вельвет"},
                 new ProdOptionsViewModel{title="Вельвет люкс-91",imglink="/Content/em/tkani/velvet/velvetlux91.jpg",cat="вельвет"},
                 new ProdOptionsViewModel{title="Вельвет люкс-92",imglink="/Content/em/tkani/velvet/velvetlux92.jpg",cat="вельвет"},
                 new ProdOptionsViewModel{title="Вельвет люкс-93",imglink="/Content/em/tkani/velvet/velvetlux93.jpg",cat="вельвет"},
                 new ProdOptionsViewModel{title="Вельвет люкс-94",imglink="/Content/em/tkani/velvet/velvetlux94.jpg",cat="вельвет"},
                 new ProdOptionsViewModel{title="Вельвет люкс-95",imglink="/Content/em/tkani/velvet/velvetlux95.jpg",cat="вельвет"},
                 new ProdOptionsViewModel{title="Вельвет люкс-96",imglink="/Content/em/tkani/velvet/velvetlux96.jpg",cat="вельвет"},
                 new ProdOptionsViewModel{title="Вельвет люкс-97",imglink="/Content/em/tkani/velvet/velvetlux97.jpg",cat="вельвет"},
                 new ProdOptionsViewModel{title="Вельвет люкс-98",imglink="/Content/em/tkani/velvet/velvetlux98.jpg",cat="вельвет"},
                 new ProdOptionsViewModel{title="Вельвет люкс-99",imglink="/Content/em/tkani/velvet/velvetlux99.jpg",cat="вельвет"},
                 new ProdOptionsViewModel{title="Вельвет люкс-100",imglink="/Content/em/tkani/velvet/velvetlux100.jpg",cat="вельвет"},

                 new ProdOptionsViewModel{title="Чарли-09",imglink="/Content/em/tkani/charli/чарли-09-500x500.jpg",cat="чарли"},
                 new ProdOptionsViewModel{title="Чарли-404",imglink="/Content/em/tkani/charli/чарли-404-500x500.jpg",cat="чарли"},
                 new ProdOptionsViewModel{title="Чарли-510",imglink="/Content/em/tkani/charli/чарли-510-500x500.jpg",cat="чарли"},
                 new ProdOptionsViewModel{title="Чарли-540",imglink="/Content/em/tkani/charli/чарли-540-500x500.jpg",cat="чарли"},
                 new ProdOptionsViewModel{title="Чарли-541",imglink="/Content/em/tkani/charli/чарли-541-500x500.jpg",cat="чарли"},
                 new ProdOptionsViewModel{title="Чарли-602",imglink="/Content/em/tkani/charli/чарли-602-500x500.jpg",cat="чарли"},
                 new ProdOptionsViewModel{title="Чарли-604",imglink="/Content/em/tkani/charli/чарли-604-500x500.jpg",cat="чарли"},
                 new ProdOptionsViewModel{title="Чарли-614",imglink="/Content/em/tkani/charli/чарли-614-500x500.jpg",cat="чарли"},
                 new ProdOptionsViewModel{title="Чарли-616",imglink="/Content/em/tkani/charli/чарли-616-500x500.jpg",cat="чарли"},
                 new ProdOptionsViewModel{title="Чарли-620",imglink="/Content/em/tkani/charli/чарли-620-500x500.jpg",cat="чарли"},
                 new ProdOptionsViewModel{title="Чарли-621",imglink="/Content/em/tkani/charli/чарли-621-500x500.jpg",cat="чарли"},
                 new ProdOptionsViewModel{title="Чарли-626",imglink="/Content/em/tkani/charli/чарли-626-500x500.jpg",cat="чарли"},
                 new ProdOptionsViewModel{title="Чарли-645",imglink="/Content/em/tkani/charli/чарли-645-500x500.jpg",cat="чарли"},
                 new ProdOptionsViewModel{title="Чарли-662",imglink="/Content/em/tkani/charli/чарли-662-500x500.jpg",cat="чарли"},
                 new ProdOptionsViewModel{title="Чарли-729",imglink="/Content/em/tkani/charli/чарли-729-500x500.jpg",cat="чарли"},
                 new ProdOptionsViewModel{title="Чарли-730",imglink="/Content/em/tkani/charli/чарли-730-500x500.jpg",cat="чарли"},
                 new ProdOptionsViewModel{title="Чарли-731",imglink="/Content/em/tkani/charli/чарли-731-500x500.jpg",cat="чарли"},
                 new ProdOptionsViewModel{title="Чарли-741",imglink="/Content/em/tkani/charli/чарли-741-500x500.jpg",cat="чарли"},

                 new ProdOptionsViewModel{title="Фокс-500",imglink="/Content/em/tkani/fox/Фокс-500-500x500.jpg",cat="фокс"},
                 new ProdOptionsViewModel{title="Фокс-502",imglink="/Content/em/tkani/fox/Фокс-502-500x500.jpg",cat="фокс"},
                 new ProdOptionsViewModel{title="Фокс-503",imglink="/Content/em/tkani/fox/Фокс-503-500x500.jpg",cat="фокс"},
                 new ProdOptionsViewModel{title="Фокс-504",imglink="/Content/em/tkani/fox/Фокс-504-500x500.jpg",cat="фокс"},
                 new ProdOptionsViewModel{title="Фокс-505",imglink="/Content/em/tkani/fox/Фокс-505-500x500.jpg",cat="фокс"},
                 new ProdOptionsViewModel{title="Фокс-506",imglink="/Content/em/tkani/fox/Фокс-506-500x500.jpg",cat="фокс"},
                 new ProdOptionsViewModel{title="Фокс-507",imglink="/Content/em/tkani/fox/Фокс-507-500x500.jpg",cat="фокс"},
                 new ProdOptionsViewModel{title="Фокс-512",imglink="/Content/em/tkani/fox/Фокс-512-500x500.jpg",cat="фокс"},
                 new ProdOptionsViewModel{title="Фокс-514",imglink="/Content/em/tkani/fox/Фокс-514-500x500.jpg",cat="фокс"},
                 new ProdOptionsViewModel{title="Фокс-516",imglink="/Content/em/tkani/fox/Фокс-516-500x500.jpg",cat="фокс"},
                 new ProdOptionsViewModel{title="Фокс-517",imglink="/Content/em/tkani/fox/Фокс-517-500x500.jpg",cat="фокс"},
                 new ProdOptionsViewModel{title="Фокс-518",imglink="/Content/em/tkani/fox/Фокс-518-500x500.jpg",cat="фокс"},
                 new ProdOptionsViewModel{title="Фокс-521",imglink="/Content/em/tkani/fox/Фокс-521-500x500.jpg",cat="фокс"},
                 new ProdOptionsViewModel{title="Фокс-545",imglink="/Content/em/tkani/fox/Фокс-545-500x500.jpg",cat="фокс"},
                 new ProdOptionsViewModel{title="Фокс-547",imglink="/Content/em/tkani/fox/Фокс-547-500x500.jpg",cat="фокс"},
                 new ProdOptionsViewModel{title="Фокс-549",imglink="/Content/em/tkani/fox/Фокс-549-500x500.jpg",cat="фокс"},

                 new ProdOptionsViewModel{title="galaxy-amber",imglink="/Content/em/tkani/galaxy/galaxy-amber.jpg",cat="гэлэкси"},
                 new ProdOptionsViewModel{title="galaxy-asphalt",imglink="/Content/em/tkani/galaxy/galaxy-asphalt.jpg",cat="гэлэкси"},
                 new ProdOptionsViewModel{title="galaxy-beige",imglink="/Content/em/tkani/galaxy/galaxy-beige.jpg",cat="гэлэкси"},
                 new ProdOptionsViewModel{title="galaxy-blue-grey",imglink="/Content/em/tkani/galaxy/galaxy-blue-grey.jpg",cat="гэлэкси"},
                 new ProdOptionsViewModel{title="galaxy-blue",imglink="/Content/em/tkani/galaxy/galaxy-blue.jpg",cat="гэлэкси"},
                 new ProdOptionsViewModel{title="galaxy-brown",imglink="/Content/em/tkani/galaxy/galaxy-brown.jpg",cat="гэлэкси"},
                 new ProdOptionsViewModel{title="galaxy-dark-brown",imglink="/Content/em/tkani/galaxy/galaxy-dark-brown.jpg",cat="гэлэкси"},
                 new ProdOptionsViewModel{title="galaxy-graphite",imglink="/Content/em/tkani/galaxy/galaxy-graphite.jpg",cat="гэлэкси"},
                 new ProdOptionsViewModel{title="galaxy-green",imglink="/Content/em/tkani/galaxy/galaxy-green.jpg",cat="гэлэкси"},
                 new ProdOptionsViewModel{title="galaxy-grey",imglink="/Content/em/tkani/galaxy/galaxy-grey.jpg",cat="гэлэкси"},
                 new ProdOptionsViewModel{title="galaxy-grey-blue",imglink="/Content/em/tkani/galaxy/galaxy-grey-blue.jpg",cat="гэлэкси"},
                 new ProdOptionsViewModel{title="galaxy-honey",imglink="/Content/em/tkani/galaxy/galaxy-honey.jpg",cat="гэлэкси"},
                 new ProdOptionsViewModel{title="galaxy-light-beige",imglink="/Content/em/tkani/galaxy/galaxy-light-beige.jpg",cat="гэлэкси"},
                 new ProdOptionsViewModel{title="galaxy-light-blue",imglink="/Content/em/tkani/galaxy/galaxy-light-blue.jpg",cat="гэлэкси"},
                 new ProdOptionsViewModel{title="galaxy-light-brown",imglink="/Content/em/tkani/galaxy/galaxy-light-brown.jpg",cat="гэлэкси"},
                 new ProdOptionsViewModel{title="galaxy-lilac",imglink="/Content/em/tkani/galaxy/galaxy-lilac.jpg",cat="гэлэкси"},
                 new ProdOptionsViewModel{title="galaxy-purple",imglink="/Content/em/tkani/galaxy/galaxy-purple.jpg",cat="гэлэкси"},
                 new ProdOptionsViewModel{title="galaxy-red",imglink="/Content/em/tkani/galaxy/galaxy-red.jpg",cat="гэлэкси"},
                 new ProdOptionsViewModel{title="galaxy-skin",imglink="/Content/em/tkani/galaxy/galaxy-skin.jpg",cat="гэлэкси"},
                 new ProdOptionsViewModel{title="galaxy-turquoise",imglink="/Content/em/tkani/galaxy/galaxy-turquoise.jpg",cat="гэлэкси"},
                 new ProdOptionsViewModel{title="galaxy-violet",imglink="/Content/em/tkani/galaxy/galaxy-violet.jpg",cat="гэлэкси"},
                 new ProdOptionsViewModel{title="galaxy-warm-beige",imglink="/Content/em/tkani/galaxy/galaxy-warm-beige.jpg",cat="гэлэкси"},
                 new ProdOptionsViewModel{title="galaxy-warm-grey",imglink="/Content/em/tkani/galaxy/galaxy-warm-grey.jpg",cat="гэлэкси"},
                 new ProdOptionsViewModel{title="galaxy-white",imglink="/Content/em/tkani/galaxy/galaxy-white.jpg",cat="гэлэкси"},






                 new ProdOptionsViewModel{title="Латте-029",imglink="/Content/em/tkani/latte/Латте-029-500x500.jpg",cat="латте"},
                 new ProdOptionsViewModel{title="Латте-100",imglink="/Content/em/tkani/latte/Латте-100-500x500.jpg",cat="латте"},
                 new ProdOptionsViewModel{title="Латте-102",imglink="/Content/em/tkani/latte/Латте-102-500x500.jpg",cat="латте"},
                 new ProdOptionsViewModel{title="Латте-103",imglink="/Content/em/tkani/latte/Латте-103-500x500.jpg",cat="латте"},
                 new ProdOptionsViewModel{title="Латте-104",imglink="/Content/em/tkani/latte/Латте-104-500x500.jpg",cat="латте"},
                 new ProdOptionsViewModel{title="Латте-111",imglink="/Content/em/tkani/latte/Латте-111-500x500.jpg",cat="латте"},
                 new ProdOptionsViewModel{title="Латте-112",imglink="/Content/em/tkani/latte/Латте-112-500x500.jpg",cat="латте"},
                 new ProdOptionsViewModel{title="Латте-115",imglink="/Content/em/tkani/latte/Латте-115-500x500.jpg",cat="латте"},
                 new ProdOptionsViewModel{title="Латте-118",imglink="/Content/em/tkani/latte/Латте-118-500x500.jpg",cat="латте"},
                 new ProdOptionsViewModel{title="Латте-221",imglink="/Content/em/tkani/latte/Латте-221-500x500.jpg",cat="латте"},
                 new ProdOptionsViewModel{title="Латте-402",imglink="/Content/em/tkani/latte/Латте-402-500x500.jpg",cat="латте"},
                 new ProdOptionsViewModel{title="Латте-404",imglink="/Content/em/tkani/latte/Латте-404-500x500.jpg",cat="латте"},
                 new ProdOptionsViewModel{title="Латте-409",imglink="/Content/em/tkani/latte/Латте-409-500x500.jpg",cat="латте"},
                 new ProdOptionsViewModel{title="Латте-410",imglink="/Content/em/tkani/latte/Латте-410-500x500.jpg",cat="латте"},
                 new ProdOptionsViewModel{title="Латте-411",imglink="/Content/em/tkani/latte/Латте-411-500x500.jpg",cat="латте"},
                 new ProdOptionsViewModel{title="Латте-412",imglink="/Content/em/tkani/latte/Латте-412-500x500.jpg",cat="латте"},
                 new ProdOptionsViewModel{title="Латте-414",imglink="/Content/em/tkani/latte/Латте-414-500x500.jpg",cat="латте"},
                 new ProdOptionsViewModel{title="Латте-417",imglink="/Content/em/tkani/latte/Латте-417-500x500.jpg",cat="латте"},
                 new ProdOptionsViewModel{title="Латте-418",imglink="/Content/em/tkani/latte/Латте-418-500x500.jpg",cat="латте"},

                 new ProdOptionsViewModel{title="Линкольн-406",imglink="/Content/em/tkani/linkoln/Линкольн-006-500x500.jpg",cat="линкольн"},
                 new ProdOptionsViewModel{title="Линкольн-011",imglink="/Content/em/tkani/linkoln/Линкольн-011-500x500.jpg",cat="линкольн"},
                 new ProdOptionsViewModel{title="Линкольн-012",imglink="/Content/em/tkani/linkoln/Линкольн-012-500x500.jpg",cat="линкольн"},
                 new ProdOptionsViewModel{title="Линкольн-013",imglink="/Content/em/tkani/linkoln/Линкольн-013-500x500.jpg",cat="линкольн"},
                 new ProdOptionsViewModel{title="Линкольн-015",imglink="/Content/em/tkani/linkoln/Линкольн-015-500x500.jpg",cat="линкольн"},
                 new ProdOptionsViewModel{title="Линкольн-057",imglink="/Content/em/tkani/linkoln/Линкольн-057-500x500.jpg",cat="линкольн"},
                 new ProdOptionsViewModel{title="Линкольн-100",imglink="/Content/em/tkani/linkoln/Линкольн-100-500x500.jpg",cat="линкольн"},
                 new ProdOptionsViewModel{title="Линкольн-101",imglink="/Content/em/tkani/linkoln/Линкольн-101-500x500.jpg",cat="линкольн"},
                 new ProdOptionsViewModel{title="Линкольн-102",imglink="/Content/em/tkani/linkoln/Линкольн-102-500x500.jpg",cat="линкольн"},
                 new ProdOptionsViewModel{title="Линкольн-103",imglink="/Content/em/tkani/linkoln/Линкольн-103-500x500.jpg",cat="линкольн"},
                 new ProdOptionsViewModel{title="Линкольн-104",imglink="/Content/em/tkani/linkoln/Линкольн-104-500x500.jpg",cat="линкольн"},
                 new ProdOptionsViewModel{title="Линкольн-111",imglink="/Content/em/tkani/linkoln/Линкольн-111-500x500.jpg",cat="линкольн"},
                 new ProdOptionsViewModel{title="Линкольн-201",imglink="/Content/em/tkani/linkoln/Линкольн-201-500x500.jpg",cat="линкольн"},
                 new ProdOptionsViewModel{title="Линкольн-202",imglink="/Content/em/tkani/linkoln/Линкольн-202-500x500.jpg",cat="линкольн"},
                 new ProdOptionsViewModel{title="Линкольн-203",imglink="/Content/em/tkani/linkoln/Линкольн-203-500x500.jpg",cat="линкольн"},
                 new ProdOptionsViewModel{title="Линкольн-204",imglink="/Content/em/tkani/linkoln/Линкольн-204-500x500.jpg",cat="линкольн"},
                 new ProdOptionsViewModel{title="Линкольн-205",imglink="/Content/em/tkani/linkoln/Линкольн-205-500x500.jpg",cat="линкольн"},
                 new ProdOptionsViewModel{title="Линкольн-206",imglink="/Content/em/tkani/linkoln/Линкольн-206-500x500.jpg",cat="линкольн"},
                 new ProdOptionsViewModel{title="Линкольн-207",imglink="/Content/em/tkani/linkoln/Линкольн-207-500x500.jpg",cat="линкольн"},
                 new ProdOptionsViewModel{title="Линкольн-208",imglink="/Content/em/tkani/linkoln/Линкольн-208-500x500.jpg",cat="линкольн"},
                 new ProdOptionsViewModel{title="Линкольн-209",imglink="/Content/em/tkani/linkoln/Линкольн-209-500x500.jpg",cat="линкольн"},
                 new ProdOptionsViewModel{title="Линкольн-210",imglink="/Content/em/tkani/linkoln/Линкольн-210-500x500.jpg",cat="линкольн"},
                 new ProdOptionsViewModel{title="Линкольн-211",imglink="/Content/em/tkani/linkoln/Линкольн-211-500x500.jpg",cat="линкольн"},
                 new ProdOptionsViewModel{title="Линкольн-212",imglink="/Content/em/tkani/linkoln/Линкольн-212-500x500.jpg",cat="линкольн"},
                 new ProdOptionsViewModel{title="Линкольн-213",imglink="/Content/em/tkani/linkoln/Линкольн-213-500x500.jpg",cat="линкольн"},
                 new ProdOptionsViewModel{title="Линкольн-214",imglink="/Content/em/tkani/linkoln/Линкольн-214-500x500.jpg",cat="линкольн"},
                 new ProdOptionsViewModel{title="Линкольн-215",imglink="/Content/em/tkani/linkoln/Линкольн-215-500x500.jpg",cat="линкольн"},
                 new ProdOptionsViewModel{title="Линкольн-221",imglink="/Content/em/tkani/linkoln/Линкольн-221-500x500.jpg",cat="линкольн"},
                 new ProdOptionsViewModel{title="Линкольн-402",imglink="/Content/em/tkani/linkoln/Линкольн-402-500x500.jpg",cat="линкольн"},
                 new ProdOptionsViewModel{title="Линкольн-418",imglink="/Content/em/tkani/linkoln/Линкольн-418-500x500.jpg",cat="линкольн"},

                 new ProdOptionsViewModel{title="Некст-01",imglink="/Content/em/tkani/next/Некст-01-500x500.jpg",cat="некст"},
                 new ProdOptionsViewModel{title="Некст-07",imglink="/Content/em/tkani/next/Некст-07-500x500.jpg",cat="некст"},
                 new ProdOptionsViewModel{title="Некст-101",imglink="/Content/em/tkani/next/Некст-101-500x500.jpg",cat="некст"},
                 new ProdOptionsViewModel{title="Некст-103",imglink="/Content/em/tkani/next/Некст-103-500x500.jpg",cat="некст"},
                 new ProdOptionsViewModel{title="Некст-13",imglink="/Content/em/tkani/next/Некст-13-500x500.jpg",cat="некст"},
                 new ProdOptionsViewModel{title="Некст-14",imglink="/Content/em/tkani/next/Некст-14-500x500.jpg",cat="некст"},
                 new ProdOptionsViewModel{title="Некст-15",imglink="/Content/em/tkani/next/Некст-15-500x500.jpg",cat="некст"},
                 new ProdOptionsViewModel{title="Некст-16",imglink="/Content/em/tkani/next/Некст-16-500x500.jpg",cat="некст"},


                 new ProdOptionsViewModel{title="Нокс-016",imglink="/Content/em/tkani/nox/Нокс-016-500x500.jpg",cat="нокс"},
                 new ProdOptionsViewModel{title="Нокс-1",imglink="/Content/em/tkani/nox/Нокс-1-500x500.jpg",cat="нокс"},
                 new ProdOptionsViewModel{title="Нокс-10",imglink="/Content/em/tkani/nox/Нокс-10-500x500.jpg",cat="нокс"},
                 new ProdOptionsViewModel{title="Нокс-11",imglink="/Content/em/tkani/nox/Нокс-11-500x500.jpg",cat="нокс"},
                 new ProdOptionsViewModel{title="Нокс-12",imglink="/Content/em/tkani/nox/Нокс-12-500x500.jpg",cat="нокс"},
                 new ProdOptionsViewModel{title="Нокс-13",imglink="/Content/em/tkani/nox/Нокс-13-500x500.jpg",cat="нокс"},
                 new ProdOptionsViewModel{title="Нокс-14",imglink="/Content/em/tkani/nox/Нокс-14-500x500.jpg",cat="нокс"},
                 new ProdOptionsViewModel{title="Нокс-15",imglink="/Content/em/tkani/nox/Нокс-15-500x500.jpg",cat="нокс"},
                 new ProdOptionsViewModel{title="Нокс-3",imglink="/Content/em/tkani/nox/Нокс-3-500x500.jpg",cat="нокс"},
                 new ProdOptionsViewModel{title="Нокс-4",imglink="/Content/em/tkani/nox/Нокс-4-500x500.jpg",cat="нокс"},
                 new ProdOptionsViewModel{title="Нокс-5",imglink="/Content/em/tkani/nox/Нокс-5-500x500.jpg",cat="нокс"},
                 new ProdOptionsViewModel{title="Нокс-6",imglink="/Content/em/tkani/nox/Нокс-6-500x500.jpg",cat="нокс"},
                 new ProdOptionsViewModel{title="Нокс-7",imglink="/Content/em/tkani/nox/Нокс-7-500x500.jpg",cat="нокс"},
                 new ProdOptionsViewModel{title="Нокс-8",imglink="/Content/em/tkani/nox/Нокс-8-500x500.jpg",cat="нокс"},
                 new ProdOptionsViewModel{title="Нокс-9",imglink="/Content/em/tkani/nox/Нокс-9-500x500.jpg",cat="нокс"},

                 new ProdOptionsViewModel{title="романтика-ароматная пудра 61",imglink="/Content/em/tkani/romantika/романтика-ароматная пудра 61.jpg",cat="романтика"},
                 new ProdOptionsViewModel{title="романтика-бархатный ирис 98",imglink="/Content/em/tkani/romantika/романтика-бархатный ирис 98.jpg",cat="романтика"},
                 new ProdOptionsViewModel{title="романтика-гранатовый закат 89",imglink="/Content/em/tkani/romantika/романтика-гранатовый закат 89.jpg",cat="романтика"},
                 new ProdOptionsViewModel{title="романтика-душистая лаванда 96",imglink="/Content/em/tkani/romantika/романтика-душистая лаванда 96.jpg",cat="романтика"},
                 new ProdOptionsViewModel{title="романтика-жемчужный берег 07",imglink="/Content/em/tkani/romantika/романтика-жемчужный берег 07.jpg",cat="романтика"},
                 new ProdOptionsViewModel{title="романтика-звездная ночь 53",imglink="/Content/em/tkani/romantika/романтика-звездная ночь 53.jpg",cat="романтика"},
                 new ProdOptionsViewModel{title="романтика-зеленый чай 42",imglink="/Content/em/tkani/romantika/романтика-зеленый чай 42.jpg",cat="романтика"},
                 new ProdOptionsViewModel{title="Романтика-лепесток жасмина 01",imglink="/Content/em/tkani/romantika/Романтика-лепесток жасмина 01.jpg",cat="романтика"},
                 new ProdOptionsViewModel{title="романтика-магия золота 63",imglink="/Content/em/tkani/romantika/романтика-магия золота 63.jpg",cat="романтика"},
                 new ProdOptionsViewModel{title="романтика-морозное утро 52",imglink="/Content/em/tkani/romantika/романтика-морозное утро 52.jpg",cat="романтика"},
                 new ProdOptionsViewModel{title="романтика-морской ветерок 54",imglink="/Content/em/tkani/romantika/романтика-морской ветерок 54.jpg",cat="романтика"},
                 new ProdOptionsViewModel{title="романтика-нежное мерцание 95",imglink="/Content/em/tkani/romantika/романтика-нежное мерцание 95.jpg",cat="романтика"},
                 new ProdOptionsViewModel{title="романтика-оливковое дерево 37",imglink="/Content/em/tkani/romantika/романтика-оливковое дерево 37.jpg",cat="романтика"},
                 new ProdOptionsViewModel{title="романтика-пурпурная фиалка 93",imglink="/Content/em/tkani/romantika/романтика-пурпурная фиалка 93.jpg",cat="романтика"},
                 new ProdOptionsViewModel{title="романтика-речная галька 43",imglink="/Content/em/tkani/romantika/романтика-речная галька 43.jpg",cat="романтика"},
                 new ProdOptionsViewModel{title="романтика-сафари парк 27",imglink="/Content/em/tkani/romantika/романтика-сафари парк 27.jpg",cat="романтика"},
                 new ProdOptionsViewModel{title="романтика-серебрянный дождь 23",imglink="/Content/em/tkani/romantika/романтика-серебрянный дождь 23.jpg",cat="романтика"},
                 new ProdOptionsViewModel{title="романтика-солнечный лайм 73",imglink="/Content/em/tkani/romantika/романтика-солнечный лайм 73.jpg",cat="романтика"},
                 new ProdOptionsViewModel{title="романтика-сосновый лес 80",imglink="/Content/em/tkani/romantika/романтика-сосновый лес 80.jpg",cat="романтика"},
                 new ProdOptionsViewModel{title="романтика-степные травы 18",imglink="/Content/em/tkani/romantika/романтика-степные травы 18.jpg",cat="романтика"},
                 new ProdOptionsViewModel{title="романтика-тропический водопад 56",imglink="/Content/em/tkani/romantika/романтика-тропический водопад 56.jpg",cat="романтика"},
                 new ProdOptionsViewModel{title="романтика-цветочный мед 62",imglink="/Content/em/tkani/romantika/романтика-цветочный мед 62.jpg",cat="романтика"},
                 new ProdOptionsViewModel{title="романтика-чайная роза 10",imglink="/Content/em/tkani/romantika/романтика-чайная роза 10.jpg",cat="романтика"},
                 new ProdOptionsViewModel{title="романтика-шоколадный ликер 33",imglink="/Content/em/tkani/romantika/романтика-шоколадный ликер 33.jpg",cat="романтика"},
                 new ProdOptionsViewModel{title="романтика-ягодный щербет 91",imglink="/Content/em/tkani/romantika/романтика-ягодный щербет 91.jpg",cat="романтика"},
                 new ProdOptionsViewModel{title="романтика 270",imglink="/Content/em/tkani/romantika/романтика 270.jpg",cat="романтика"},
                 new ProdOptionsViewModel{title="романтика 401",imglink="/Content/em/tkani/romantika/романтика 401.jpg",cat="романтика"},
                 new ProdOptionsViewModel{title="романтика 402",imglink="/Content/em/tkani/romantika/романтика 402.jpg",cat="романтика"},
                 new ProdOptionsViewModel{title="романтика 403",imglink="/Content/em/tkani/romantika/романтика 403.jpg",cat="романтика"},
                 new ProdOptionsViewModel{title="романтика 97",imglink="/Content/em/tkani/romantika/романтика 97.jpg",cat="романтика"},


                  new ProdOptionsViewModel{title="скай-вельвет 1",imglink="/Content/em/tkani/sky-velvet/1.jpg",cat="скай-вельвет"},
                  new ProdOptionsViewModel{title="скай-вельвет 10",imglink="/Content/em/tkani/sky-velvet/10.jpg",cat="скай-вельвет"},
                  new ProdOptionsViewModel{title="скай-вельвет 11",imglink="/Content/em/tkani/sky-velvet/11.jpg",cat="скай-вельвет"},
                  new ProdOptionsViewModel{title="скай-вельвет 12",imglink="/Content/em/tkani/sky-velvet/12.jpg",cat="скай-вельвет"},
                  new ProdOptionsViewModel{title="скай-вельвет 13",imglink="/Content/em/tkani/sky-velvet/13.jpg",cat="скай-вельвет"},
                  new ProdOptionsViewModel{title="скай-вельвет 14",imglink="/Content/em/tkani/sky-velvet/14.jpg",cat="скай-вельвет"},
                  new ProdOptionsViewModel{title="скай-вельвет 15",imglink="/Content/em/tkani/sky-velvet/15.jpg",cat="скай-вельвет"},
                  new ProdOptionsViewModel{title="скай-вельвет 16",imglink="/Content/em/tkani/sky-velvet/16.jpg",cat="скай-вельвет"},
                  new ProdOptionsViewModel{title="скай-вельвет 17",imglink="/Content/em/tkani/sky-velvet/17.jpg",cat="скай-вельвет"},
                  new ProdOptionsViewModel{title="скай-вельвет 18",imglink="/Content/em/tkani/sky-velvet/18.jpg",cat="скай-вельвет"},
                  new ProdOptionsViewModel{title="скай-вельвет 19",imglink="/Content/em/tkani/sky-velvet/19.jpg",cat="скай-вельвет"},
                  new ProdOptionsViewModel{title="скай-вельвет 2",imglink="/Content/em/tkani/sky-velvet/2.jpg",cat="скай-вельвет"},
                  new ProdOptionsViewModel{title="скай-вельвет 3",imglink="/Content/em/tkani/sky-velvet/3.jpg",cat="скай-вельвет"},
                  new ProdOptionsViewModel{title="скай-вельвет 4",imglink="/Content/em/tkani/sky-velvet/4.jpg",cat="скай-вельвет"},
                  new ProdOptionsViewModel{title="скай-вельвет 5",imglink="/Content/em/tkani/sky-velvet/5.jpg",cat="скай-вельвет"},
                  new ProdOptionsViewModel{title="скай-вельвет 6",imglink="/Content/em/tkani/sky-velvet/6.jpg",cat="скай-вельвет"},
                  new ProdOptionsViewModel{title="скай-вельвет 7",imglink="/Content/em/tkani/sky-velvet/7.jpg",cat="скай-вельвет"},
                  new ProdOptionsViewModel{title="скай-вельвет 8",imglink="/Content/em/tkani/sky-velvet/8.jpg",cat="скай-вельвет"},
                  new ProdOptionsViewModel{title="скай-вельвет 9",imglink="/Content/em/tkani/sky-velvet/9.jpg",cat="скай-вельвет"},


                  new ProdOptionsViewModel{title="софт-тач 1",imglink="/Content/em/tkani/soft-touch/1.jpg",cat="софт-тач"},
                  new ProdOptionsViewModel{title="софт-тач 10",imglink="/Content/em/tkani/soft-touch/10.jpg",cat="софт-тач"},
                  new ProdOptionsViewModel{title="софт-тач 11",imglink="/Content/em/tkani/soft-touch/11.jpg",cat="софт-тач"},
                  new ProdOptionsViewModel{title="софт-тач 12",imglink="/Content/em/tkani/soft-touch/12.jpg",cat="софт-тач"},
                  new ProdOptionsViewModel{title="софт-тач 13",imglink="/Content/em/tkani/soft-touch/13.jpg",cat="софт-тач"},
                  new ProdOptionsViewModel{title="софт-тач 14",imglink="/Content/em/tkani/soft-touch/14.jpg",cat="софт-тач"},
                  new ProdOptionsViewModel{title="софт-тач 15",imglink="/Content/em/tkani/soft-touch/15.jpg",cat="софт-тач"},
                  new ProdOptionsViewModel{title="софт-тач 16",imglink="/Content/em/tkani/soft-touch/16.jpg",cat="софт-тач"},
                  new ProdOptionsViewModel{title="софт-тач 17",imglink="/Content/em/tkani/soft-touch/17.jpg",cat="софт-тач"},
                  new ProdOptionsViewModel{title="софт-тач 2",imglink="/Content/em/tkani/soft-touch/2.jpg",cat="софт-тач"},
                  new ProdOptionsViewModel{title="софт-тач 3",imglink="/Content/em/tkani/soft-touch/3.jpg",cat="софт-тач"},
                  new ProdOptionsViewModel{title="софт-тач 4",imglink="/Content/em/tkani/soft-touch/4.jpg",cat="софт-тач"},
                  new ProdOptionsViewModel{title="софт-тач 5",imglink="/Content/em/tkani/soft-touch/5.jpg",cat="софт-тач"},
                  new ProdOptionsViewModel{title="софт-тач 6",imglink="/Content/em/tkani/soft-touch/6.jpg",cat="софт-тач"},
                  new ProdOptionsViewModel{title="софт-тач 7",imglink="/Content/em/tkani/soft-touch/7.jpg",cat="софт-тач"},
                  new ProdOptionsViewModel{title="софт-тач 8",imglink="/Content/em/tkani/soft-touch/8.jpg",cat="софт-тач"},
                  new ProdOptionsViewModel{title="софт-тач 9",imglink="/Content/em/tkani/soft-touch/9.jpg",cat="софт-тач"},


                  new ProdOptionsViewModel{title="супернова 1",imglink="/Content/em/tkani/supernova/1.jpg",cat="супернова"},
                  new ProdOptionsViewModel{title="супернова 10",imglink="/Content/em/tkani/supernova/10.jpg",cat="супернова"},
                  new ProdOptionsViewModel{title="супернова 11",imglink="/Content/em/tkani/supernova/11.jpg",cat="супернова"},
                  new ProdOptionsViewModel{title="супернова 12",imglink="/Content/em/tkani/supernova/12.jpg",cat="супернова"},
                  new ProdOptionsViewModel{title="супернова 13",imglink="/Content/em/tkani/supernova/13.jpg",cat="супернова"},
                  new ProdOptionsViewModel{title="супернова 14",imglink="/Content/em/tkani/supernova/14.jpg",cat="супернова"},
                  new ProdOptionsViewModel{title="супернова 15",imglink="/Content/em/tkani/supernova/15.jpg",cat="супернова"},
                  new ProdOptionsViewModel{title="супернова 16",imglink="/Content/em/tkani/supernova/16.jpg",cat="супернова"},
                  new ProdOptionsViewModel{title="супернова 17",imglink="/Content/em/tkani/supernova/17.jpg",cat="супернова"},
                  new ProdOptionsViewModel{title="супернова 18",imglink="/Content/em/tkani/supernova/18.jpg",cat="супернова"},
                  new ProdOptionsViewModel{title="супернова 19",imglink="/Content/em/tkani/supernova/19.jpg",cat="супернова"},
                  new ProdOptionsViewModel{title="супернова 2",imglink="/Content/em/tkani/supernova/2.jpg",cat="супернова"},
                  new ProdOptionsViewModel{title="супернова 20",imglink="/Content/em/tkani/supernova/20.jpg",cat="супернова"},
                  new ProdOptionsViewModel{title="супернова 21",imglink="/Content/em/tkani/supernova/21.jpg",cat="супернова"},
                  new ProdOptionsViewModel{title="супернова 22",imglink="/Content/em/tkani/supernova/22.jpg",cat="супернова"},
                  new ProdOptionsViewModel{title="супернова 23",imglink="/Content/em/tkani/supernova/23.jpg",cat="супернова"},
                  new ProdOptionsViewModel{title="супернова 24",imglink="/Content/em/tkani/supernova/24.jpg",cat="супернова"},
                  new ProdOptionsViewModel{title="супернова 25",imglink="/Content/em/tkani/supernova/25.jpg",cat="супернова"},
                  new ProdOptionsViewModel{title="супернова 3",imglink="/Content/em/tkani/supernova/3.jpg",cat="супернова"},
                  new ProdOptionsViewModel{title="супернова 4",imglink="/Content/em/tkani/supernova/4.jpg",cat="супернова"},
                  new ProdOptionsViewModel{title="супернова 5",imglink="/Content/em/tkani/supernova/5.jpg",cat="супернова"},
                  new ProdOptionsViewModel{title="супернова 6",imglink="/Content/em/tkani/supernova/6.jpg",cat="супернова"},
                  new ProdOptionsViewModel{title="супернова 7",imglink="/Content/em/tkani/supernova/7.jpg",cat="супернова"},
                  new ProdOptionsViewModel{title="супернова 8",imglink="/Content/em/tkani/supernova/8.jpg",cat="супернова"},
                  new ProdOptionsViewModel{title="супернова 9",imglink="/Content/em/tkani/supernova/9.jpg",cat="супернова"},

                  new ProdOptionsViewModel{title="талисман 1",imglink="/Content/em/tkani/talisman/talisman1.jpg",cat="талисман"},
                  new ProdOptionsViewModel{title="талисман 2",imglink="/Content/em/tkani/talisman/talisman2.jpg",cat="талисман"},
                  new ProdOptionsViewModel{title="талисман 3",imglink="/Content/em/tkani/talisman/talisman3.jpg",cat="талисман"},
                  new ProdOptionsViewModel{title="талисман 4",imglink="/Content/em/tkani/talisman/talisman4.jpg",cat="талисман"},
                  new ProdOptionsViewModel{title="талисман 5",imglink="/Content/em/tkani/talisman/talisman5.jpg",cat="талисман"},
                  new ProdOptionsViewModel{title="талисман 6",imglink="/Content/em/tkani/talisman/talisman6.jpg",cat="талисман"},
                  new ProdOptionsViewModel{title="талисман 7",imglink="/Content/em/tkani/talisman/talisman7.jpg",cat="талисман"},
                  new ProdOptionsViewModel{title="талисман 8",imglink="/Content/em/tkani/talisman/talisman8.jpg",cat="талисман"},
                  new ProdOptionsViewModel{title="талисман 9",imglink="/Content/em/tkani/talisman/talisman9.jpg",cat="талисман"},
                  new ProdOptionsViewModel{title="талисман 10",imglink="/Content/em/tkani/talisman/talisman10.jpg",cat="талисман"},
                  new ProdOptionsViewModel{title="талисман 11",imglink="/Content/em/tkani/talisman/talisman11.jpg",cat="талисман"},
                  new ProdOptionsViewModel{title="талисман 12",imglink="/Content/em/tkani/talisman/talisman12.jpg",cat="талисман"},
                  new ProdOptionsViewModel{title="талисман 13",imglink="/Content/em/tkani/talisman/talisman13.jpg",cat="талисман"},
                  new ProdOptionsViewModel{title="талисман 14",imglink="/Content/em/tkani/talisman/talisman14.jpg",cat="талисман"},
                  new ProdOptionsViewModel{title="талисман 15",imglink="/Content/em/tkani/talisman/talisman15.jpg",cat="талисман"},



                  new ProdOptionsViewModel{title="вензо-софт 2",imglink="/Content/em/tkani/venzo-soft/2.jpg",cat="вензо-софт"},
                  new ProdOptionsViewModel{title="вензо-софт 3",imglink="/Content/em/tkani/venzo-soft/3.jpg",cat="вензо-софт"},
                  new ProdOptionsViewModel{title="вензо-софт 4",imglink="/Content/em/tkani/venzo-soft/4.jpg",cat="вензо-софт"},
                  new ProdOptionsViewModel{title="вензо-софт 5",imglink="/Content/em/tkani/venzo-soft/5.jpg",cat="вензо-софт"},
                  new ProdOptionsViewModel{title="вензо-софт 6",imglink="/Content/em/tkani/venzo-soft/6.jpg",cat="вензо-софт"},
                  new ProdOptionsViewModel{title="вензо-софт 7",imglink="/Content/em/tkani/venzo-soft/7.jpg",cat="вензо-софт"},
                  new ProdOptionsViewModel{title="вензо-софт 8",imglink="/Content/em/tkani/venzo-soft/8.jpg",cat="вензо-софт"},
                  new ProdOptionsViewModel{title="вензо-софт 9",imglink="/Content/em/tkani/venzo-soft/9.jpg",cat="вензо-софт"},
                  new ProdOptionsViewModel{title="вензо-софт 10",imglink="/Content/em/tkani/venzo-soft/10.jpg",cat="вензо-софт"},
                  new ProdOptionsViewModel{title="вензо-софт 11",imglink="/Content/em/tkani/venzo-soft/11.jpg",cat="вензо-софт"},
                  new ProdOptionsViewModel{title="вензо-софт 12",imglink="/Content/em/tkani/venzo-soft/12.jpg",cat="вензо-софт"},
                  new ProdOptionsViewModel{title="вензо-софт 13",imglink="/Content/em/tkani/venzo-soft/13.jpg",cat="вензо-софт"},
                  new ProdOptionsViewModel{title="вензо-софт 14",imglink="/Content/em/tkani/venzo-soft/14.jpg",cat="вензо-софт"},
                  new ProdOptionsViewModel{title="вензо-софт 15",imglink="/Content/em/tkani/venzo-soft/15.jpg",cat="вензо-софт"},
                  new ProdOptionsViewModel{title="вензо-софт 16",imglink="/Content/em/tkani/venzo-soft/16.jpg",cat="вензо-софт"},
                  new ProdOptionsViewModel{title="вензо-софт 17",imglink="/Content/em/tkani/venzo-soft/17.jpg",cat="вензо-софт"},

            };
            return clothList;
        }


        public static List<ProdOptionsViewModel> GetColor()
        {

            var colorList = new List<ProdOptionsViewModel>(){
                  new ProdOptionsViewModel{title="Белый",imglink="/Content/em/okras/white-500x400.png"},
                new ProdOptionsViewModel{title="Серый",imglink="/Content/em/okras/gray.jpg"},
                new ProdOptionsViewModel{title="Слоновая кость",imglink="/Content/em/okras/slon-500x400.png"},
                new ProdOptionsViewModel{title="Черный",imglink="/Content/em/okras/black-500x400.png"},
                new ProdOptionsViewModel{title="Венге",imglink="/Content/em/okras/venge-500x400.png"},
                new ProdOptionsViewModel{title="Шоколад",imglink="/Content/em/okras/shokol-500x400.png"}



            };
            return colorList;
        }
    }
}